/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainersRouteImport } from './routes/trainers'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as EnquiryRouteImport } from './routes/enquiry'
import { Route as BookPtRouteImport } from './routes/book-pt'
import { Route as BookGroupClassRouteImport } from './routes/book-group-class'
import { Route as IndexRouteImport } from './routes/index'

const TrainersRoute = TrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiryRoute = EnquiryRouteImport.update({
  id: '/enquiry',
  path: '/enquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const BookPtRoute = BookPtRouteImport.update({
  id: '/book-pt',
  path: '/book-pt',
  getParentRoute: () => rootRouteImport,
} as any)
const BookGroupClassRoute = BookGroupClassRouteImport.update({
  id: '/book-group-class',
  path: '/book-group-class',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book-group-class': typeof BookGroupClassRoute
  '/book-pt': typeof BookPtRoute
  '/enquiry': typeof EnquiryRoute
  '/feedback': typeof FeedbackRoute
  '/gallery': typeof GalleryRoute
  '/offers': typeof OffersRoute
  '/packages': typeof PackagesRoute
  '/reviews': typeof ReviewsRoute
  '/trainers': typeof TrainersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book-group-class': typeof BookGroupClassRoute
  '/book-pt': typeof BookPtRoute
  '/enquiry': typeof EnquiryRoute
  '/feedback': typeof FeedbackRoute
  '/gallery': typeof GalleryRoute
  '/offers': typeof OffersRoute
  '/packages': typeof PackagesRoute
  '/reviews': typeof ReviewsRoute
  '/trainers': typeof TrainersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book-group-class': typeof BookGroupClassRoute
  '/book-pt': typeof BookPtRoute
  '/enquiry': typeof EnquiryRoute
  '/feedback': typeof FeedbackRoute
  '/gallery': typeof GalleryRoute
  '/offers': typeof OffersRoute
  '/packages': typeof PackagesRoute
  '/reviews': typeof ReviewsRoute
  '/trainers': typeof TrainersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book-group-class'
    | '/book-pt'
    | '/enquiry'
    | '/feedback'
    | '/gallery'
    | '/offers'
    | '/packages'
    | '/reviews'
    | '/trainers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book-group-class'
    | '/book-pt'
    | '/enquiry'
    | '/feedback'
    | '/gallery'
    | '/offers'
    | '/packages'
    | '/reviews'
    | '/trainers'
  id:
    | '__root__'
    | '/'
    | '/book-group-class'
    | '/book-pt'
    | '/enquiry'
    | '/feedback'
    | '/gallery'
    | '/offers'
    | '/packages'
    | '/reviews'
    | '/trainers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookGroupClassRoute: typeof BookGroupClassRoute
  BookPtRoute: typeof BookPtRoute
  EnquiryRoute: typeof EnquiryRoute
  FeedbackRoute: typeof FeedbackRoute
  GalleryRoute: typeof GalleryRoute
  OffersRoute: typeof OffersRoute
  PackagesRoute: typeof PackagesRoute
  ReviewsRoute: typeof ReviewsRoute
  TrainersRoute: typeof TrainersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trainers': {
      id: '/trainers'
      path: '/trainers'
      fullPath: '/trainers'
      preLoaderRoute: typeof TrainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiry': {
      id: '/enquiry'
      path: '/enquiry'
      fullPath: '/enquiry'
      preLoaderRoute: typeof EnquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-pt': {
      id: '/book-pt'
      path: '/book-pt'
      fullPath: '/book-pt'
      preLoaderRoute: typeof BookPtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-group-class': {
      id: '/book-group-class'
      path: '/book-group-class'
      fullPath: '/book-group-class'
      preLoaderRoute: typeof BookGroupClassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookGroupClassRoute: BookGroupClassRoute,
  BookPtRoute: BookPtRoute,
  EnquiryRoute: EnquiryRoute,
  FeedbackRoute: FeedbackRoute,
  GalleryRoute: GalleryRoute,
  OffersRoute: OffersRoute,
  PackagesRoute: PackagesRoute,
  ReviewsRoute: ReviewsRoute,
  TrainersRoute: TrainersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
